### ISSUE TITLE
Delay handling of path parsing errors?

### ISSUE THREAD

**Issue by jgillich** [chill-rs/chill#47]
Currently, executing an action requires unwrapping of two results:
```
let foo = db.action().unwrap().run().unwrap();
```
For some actions, there are a few more, like when you're receiving a document:
```
let content = foo.get_conent().unwrap();
```
This results in a lot of nested `try!` calls. IMO, we should change the actions to return `Self` and store the path as `Result<Path, Error>` that gets unwrapped in `run()`. That's also how [hyper does it](https://github.com/hyperium/hyper/blob/028f5864324f95d4d9007c304358b6e7b91743fc/src/client/mod.rs#L202).

**Comment by cmbrandenburg** [comment]
Duplicate, see #34.

I was uncertain about the design when I cut the v0.1.0 release and decided to keep it the way it is now because it's easier to go from fallible to infallible than from infallible to fallible. Also, the Rust `?` operator is coming which will replace `try!` and make things a little better—or so they say. Nevertheless, I prefer infallibility and have scheduled the change for v0.2.0.

**Comment by jgillich** [comment]
Note that there are cases where you can't use `?`, for example in Iron handlers. They must return a Iron::Error, which is why they have their own try macro `itry!`.
